### ISSUE TITLE
[Specification] Use string for all the keys

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/Core#112]
Currently the sub keys of the hashes use symbols (e.g. `source` the source params like `:git`). There is already logic there to handle the conversion when appropriate... but all the keys should be used as strings and converted, if needed, by the consumer.

This would also lead to a cleaner Lockfile:

``` yaml
EXTERNAL SOURCES:
  IFBKCampground:
    :git: https://github.com/irrationalfab/IFBKCampground.git
  IFBKThirtySeven:
    :path: ../../IFBKThirtySeven
  IRFAutoCompletionKit:
    :git: https://github.com/irrationalfab/IRFAutoCompletionKit
  IRFNavigationKit:
    :git: https://github.com/irrationalfab/IRFNavigationKit.git)
```

Related: https://github.com/CocoaPods/CocoaPods/issues/1058#issuecomment-40549156
## 

@alloy we need to double check this for trunk because the JSON podspec return strings.
